### PR TITLE
Add Instagram provider to baseConfig.js

### PR DESCRIPTION
**Pull request by lukechilds**
Adds OAuth 2.0 provider for Instagram

### CODE REVIEW

**Comment by paulvanbladel** [comment]
Many thanks.
I need to generate now a new version for jspm to get this update.
Keep you posted when it is ready.
Cheers

**Comment by lukechilds** [comment]
Two secs, don't do it yet!

Just spotted I've left the scope for my app in, it should probs be 'basic' by default.

**Comment by paulvanbladel** [comment]
Ok, no worries.

**Comment by lukechilds** [comment]
OK, all good.
https://github.com/paulvanbladel/aurelia-auth/pull/22

**Pull request merged**
