### PR TITLE
Made arguments optional

### PR DESCRIPTION
**Pull request by RWOverdijk**
I don't use "email" as key. So I made it optional. Also, boo for tabs. *grabs popcorn*

### CODE REVIEW

**Comment by paulvanbladel** [comment]
done. v0.9.6
The plugin is renamed also to aurelia-auth :)

**Comment by RWOverdijk** [comment]
Hoorah. Thanks. Small Q (so I don't have to open a new issue). Are you married to tabs, or open to reformatting to the standards (2 spaces)? Asking this carefully because I don't want to unleash a holy war.

**Comment by paulvanbladel** [comment]
you are welcome.
Haha, I'm completely ignorant when it comes to tabs. You have to forgive me, my primary background is .Net and visual studio and these new editors (i'm currently using sublimetext) are all new for me, so ... please learn me some new tricks but first explain me what's wrong with tabs :)

**Comment by wshayes** [comment]
FYI -- https://lostechies.com/jimmybogard/2012/03/07/tabs-versus-spaces-spaces-won/

Not wanting to join a holy war - mostly need to settle on either spaces or tabs, but it seems like spaces are gaining ground and definitely preferred by the rest of the Aurelia project.  

Thank you very much for the plugin! - I'm happy to use whatever you decide.

Here is the .editorconfig that comes with the Aurelia Skeleton project:

    ~/code/aurelia/skel$ more .editorconfig
    # EditorConfig is awesome: http://EditorConfig.org
    # top-most EditorConfig file
    root = true

    # Unix-style newlines with a newline ending every file
    [*] 
    end_of_line = lf
    insert_final_newline = true

    # 2 space indentation
    [**.*]
    indent_style = space
    indent_size = 2

**Comment by RWOverdijk** [comment]
@wshayes :+1:

**Comment by RWOverdijk** [comment]
Also, maybe join gitter! :) I have some questions, mainly about configuring the http client. Also it's just a good place to be :)

**Comment by paulvanbladel** [comment]
@wshayes thanks for learning an old dog new tricks, appreciated.
@RWOverdijk do I need to configure something in gitter, so that I can get a notification of your question?

**Comment by RWOverdijk** [comment]
@paulvanbladel No it's just a chat. We're in https://gitter.im/Aurelia/Discuss

**Comment by paulvanbladel** [comment]
@RWOverdijk : if i simply add the .editorconfig in the project root, we are all set?

**Pull request merged**
